version: '3.9'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration/postgresql/V1__initTables.sql:/docker-entrypoint-initdb.d/V1__initTables.sql
    environment:
      - 'POSTGRES_DB=pichincha'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./db/pgadmin-data:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test_pablo@pichincha.com
      PGADMIN_DEFAULT_PASSWORD: pichincha123
      PGADMIN_LISTEN_PORT: 8100
    ports:
      - "8100:8100"
    depends_on:
      - postgres

  app:
    container_name: app
    image: openjdk:17-jdk-alpine
    platform: "linux/amd64"
    build: ./
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/pichincha
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres